package com.sinc.sat.analy.model.vo;

public class PositiveVO {
	private int		posit_no;
	private String	k1;
	private String	k2;
	private String	k3;
	private String	k4;
	private String	k5;
	private String	k6;
	private String	k7;
	private String	k8;
	private String	k9;
	private String	k10;
	private String	k11;
	private String	k12;
	private String	k13;
	private String	k14;
	private String	k15;
	private String	k16;
	private String	k17;
	private String	k18;
	private String	k19;
	private String	f20;
	private String	w1;
	private String	w2;
	private String	w3;
	private String	w4;
	private String	w5;
	private String	w6;
	private String	w7;
	private String	w8;
	private String	w9;
	private String	w10;
	private String	w11;
	private String	w12;
	private String	w13;
	private String	w14;
	private String	w15;
	private String	w16;
	private String	w17;
	private String	w18;
	private String	w19;
	private String	w20;
}
